name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: windows-latest

    env:
      SONAR_PROJECT_KEY: Bunnn12_SnakeAndLaddersFinalProject
      SONAR_ORG: bunnn12
      SONAR_HOST_URL: https://sonarcloud.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore SnakeAndLaddersFinalProject.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Begin
        run: >
          dotnet sonarscanner begin
          /k:"${{ env.SONAR_PROJECT_KEY }}"
          /o:"${{ env.SONAR_ORG }}"
          /d:sonar.host.url="${{ env.SONAR_HOST_URL }}"
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.dotnet.enableRoslynAnalyzers=true

      - name: Build (usa .editorconfig y analyzers)
        run: msbuild SnakeAndLaddersFinalProject.sln /p:Configuration=Debug

      - name: SonarCloud End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
